Feature/fragment mark
MikhailGorbach/_Vector pull request #12
Opened 2021-11-06 12:34 UTC by MikhailGorbach

2021-11-07 19:09 UTC, mist962 requested changes

2021-11-07 19:09 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                if (location != "") {
кажется можно заменить на isNotBlank()

2021-11-07 19:09 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                            mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(latLng, 12f))
вынеси приватную const val NAME и задай такое имя чтобя понял что это за цафра 12

2021-11-07 19:09 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                        val addressList: List<Address> = geocoder.getFromLocationName(location, 1)
почему тут 1

2021-11-07 19:09 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                val descriptionTextInputLayout = placeFromView.findViewById<TextInputLayout>(R.id.descriptionTextInputLayout)
не нравится мне тут findViewById, хочу видеть тут binding

2021-11-07 19:09 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                .show()
не нравится мне такое, я бы хотел чтобы ты сделал DialogFragment, чтобы там вся эта логина была, и меньше кода, вроде бы

2021-11-07 19:09 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +            != PackageManager.PERMISSION_GRANTED
слишком сложный иф и непонятный, вынеси это в отдельную функцию которая будет возвращать результат этих проверок, и дай ей понятное имя, чтобы небыло такой безумной фигни

2021-11-07 20:24 UTC, MikhailGorbach commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                if (location != "") {
Можно, заменил

2021-11-07 20:25 UTC, MikhailGorbach commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                            mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(latLng, 12f))
Сделано. Цифра для масштаба карты. Переменную так и назвал.

2021-11-07 20:32 UTC, MikhailGorbach commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +                        val addressList: List<Address> = geocoder.getFromLocationName(location, 1)
Заменил List<Address> на Address, потому что нужна только одна конкретная локация. Вынес в переменную const val

2021-11-08 10:39 UTC, MikhailGorbach commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +            != PackageManager.PERMISSION_GRANTED
Вынес в отдельную функцию. Дал понятное название.

2021-11-08 11:25 UTC, mist962 requested changes

2021-11-08 11:25 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +    }
вынеси выше class MapFragment : Fragment(), OnMapReadyCallback, не нужно в компаньен ложить, это делает их статикой, что дополнительно потребляет память

2021-11-08 11:25 UTC, mist962 commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +        != PackageManager.PERMISSION_GRANTED)
ам можно без переноса, сложно читатется условие

2021-11-08 11:29 UTC, MikhailGorbach commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +    }
Понял, вынес.

2021-11-08 12:17 UTC, MikhailGorbach commented on app/src/main/java/com/example/vector/ui/map/MapFragment.kt
> +        != PackageManager.PERMISSION_GRANTED)
Можно

2021-11-08 12:39 UTC, merged